task_type = "regression"


[network]
load_path = "models/jastrow_regression/06092023_094742/checkpoint_model.pt"
batch_size = 64

[saving_folders]
results_folder = "results/decoder/jastrow_regression/test"

[[datasets.validation]]
name = "eval_aligned"
annotation_file = "datasets/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "aligned" }


[[datasets.validation]]
name = "val_illusory"
annotation_file = "datasets/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "illusory" }
