task_type = "regression"


[network]
load_path = "models/examples/decoder/jastrow_regression/trained_model/checkpoint_model.pt"
batch_size = 16

[saving_folders]
results_folder = "results/examples/decoder/jastrow_regression/test"

[[eval.datasets]]
name = "eval_aligned"
annotation_file = "datasets_examples/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "aligned" }


[[eval.datasets]]
name = "val_illusory"
annotation_file = "datasets_examples/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "illusory" }


[transformation]
translation = false
scale = false
rotation = false
rotation = false
