task_type = "regression"

[training]
evaluate_during_training = true

[saving_folders]
results_folder = "results/decoder/jastrow_regression"
model_output_folder = "models/decoder/jastrow_regression"

[datasets.training]
name = "train_random"
annotation_file = "datasets/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "random" }

[[datasets.validation]]
name = "eval_aligned"
annotation_file = "datasets/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "aligned" }


[[datasets.validation]]
name = "val_illusory"
annotation_file = "datasets/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "illusory" }


[monitoring]
neptune_proj_name = false
