# See src/utils/compute_distance/default_distance_config.toml for a detailed explanation of the options.
[basic_info]
annotation_file_path = "datasets_examples/CSE_CIE_dots_small/annotation.csv"
match_factors = "" # ["SampleId"]
factor_variable = "PairA/B"
reference_level = "a"

[basic_info.filter_factor_level]
Type = "single"


[options]
pretraining = "ImageNet'"

[saving_folders]
results_folder = "results/examples/distance_similarity/high_level_vision/CSE_CIE_dots"

[transformation]
[transformation.values]
translation = false
rotation = false
scale = false