# See src/utils/compute_distance/default_distance_config.toml for a detailed explanation of the options.
[basic_info]
annotation_file_path = "datasets_examples/emergent_features/annotation.csv"
match_factors = ""
factor_variable = "PairA/B"
reference_level = "a"

[basic_info.filter_factor_level]
Type = "single"


[options]
pretraining = "ImageNet'"

[saving_folders]
results_folder = "results/examples/similarity_judgments/low_mid_level_vision/emergent_features"

[transformation]
[transformation.values]
translation_X = false
translation_Y = false
rotation = false
scale = false
