["src/datasets_generation/coding_of_shapes/volumetric_vs_surface/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
object_longest_side = 100
output_folder = "data/coding_of_shapes/volumetric_vs_surface"

["src/datasets_generation/coding_of_shapes/similarity_NAPvsMP_3D/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
stroke_color = ""
output_folder = "data/coding_of_shapes/NAPvsMP_geons"

["src/datasets_generation/coding_of_shapes/NAPvsMP_2D_lines/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
output_folder = "data/coding_of_shapes/NAPvsMP_2D_lines"

["src/datasets_generation/high_level_vision/size_constancy_ponzo/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_scrambled_samples = 100
num_illusory_samples = 100
num_rail_lines = 5
train_with_rnd_col_lines = false
output_folder = "data/high_level_vision/size_constancy_ponzo"

["src/datasets_generation/high_level_vision/decomposition/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
moving_distance = 60
shape_color = [ 255, 0, 0,]
output_folder = "data/high_level_vision/decomposition"

["src/datasets_generation/high_level_vision/same_different_task/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
type_dataset = "all"
size_shapes = 20
output_folder = "data/high_level_vision/same_different_task"

["src/datasets_generation/high_level_vision/gridded_images/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix"
object_longest_side = 100
grid_degree = 45
grid_size = 8
grid_thickness = 4
output_folder = "data/high_level_vision/gridded_images"

["src/datasets_generation/low_level_vision/ebbinghaus_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
output_folder = "data/low_level_vision/ebbinghaus_illusion"

["src/datasets_generation/low_level_vision/contour_completion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
circle_color = [ 255, 255, 255,]
square_color = [ 0, 0, 0,]
output_folder = "data/low_level_vision/contour_completion"

["src/datasets_generation/low_level_vision/tilt_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_only_center_samples = 100
num_center_context_samples = 100
output_folder = "data/low_level_vision/tilt_illusion"

["src/datasets_generation/low_level_vision/webers_law/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_per_length = 100
max_line_length = 50
min_line_length = 5
interval_line_length = 1
output_folder = "data/low_level_vision/webers_law_length"

["src/datasets_generation/low_level_vision/muller_lyer_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_scrambled_samples = 100
num_illusory_samples = 100
output_folder = "data/low_level_vision/muller_lyer_illusion"

["src/datasets_generation/low_level_vision/jastrow_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_illusory_samples = 50
num_random_samples = 50
num_aligned_samples = 50
output_folder = "data/low_level_vision/jastrow_illusion"

["src/datasets_generation/gestalt/thatcher_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
face_folder = "assets/celebA_sample/normal"
output_folder = "data/gestalt/thatcher_illusion"
regenerate = true

["src/datasets_generation/gestalt/dotted_linedrawings/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
object_longest_side = 100
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
dot_distance = 5
dot_size = 1
output_folder = "data/gestalt/dotted_linedrawings"

["src/datasets_generation/gestalt/leuven_embedded_figures_test/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
output_folder = "data/gestalt/leuven_embedded_figures_test"

["src/datasets_generation/gestalt/CSE_CIE_dots/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
output_folder = "data/gestalt/CSE_CIE_dots"

["src/datasets_generation/gestalt/texturized_linedrawings/generate_dataset_lines.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
num_samples = 50
object_longest_side = 100
density = 1.8
output_folder = "data/gestalt/texturized_linedrawings_lines"

["src/datasets_generation/gestalt/texturized_linedrawings/generate_dataset_chars.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
num_samples = 50
object_longest_side = 150
background_char = "\\"
foreground_char = "."
output_folder = "data/gestalt/texturized_linedrawings_chars"

["src/datasets_generation/gestalt/un_crowding/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_vernier_inside = 100
num_samples_vernier_outside = 100
random_size = true
output_folder = "data/gestalt/un_crowding"

["src/datasets_generation/gestalt/embedded_figures/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_polygons = 100
num_samples_embedded_polygons = 100
shape_size = 45
debug_mode = false
output_folder = "data/gestalt/embedded_figures"
