
["src/datasets_generation/gestalt/CSE_CIE_dots/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
output_folder = "datasets_lite/gestalt/CSE_CIE_dots"