["src/generate_datasets/coding_of_shapes/volumetric_vs_surface/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
object_longest_side = 100
output_folder = "datasets_lite/coding_of_shapes/volumetric_vs_surface"

["src/generate_datasets/coding_of_shapes/NAPvsMP_2D_lines/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
output_folder = "datasets_lite/coding_of_shapes/NAPvsMP_2D_lines"

["src/generate_datasets/coding_of_shapes/NAPvsMP_3D_geons/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
stroke_color = ""
output_folder = "datasets_lite/coding_of_shapes/NAPvsMP_3D_geons"

["src/generate_datasets/high_level_vision/decomposition/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
moving_distance = 60
shape_color = [ 255, 255, 255,]
output_folder = "datasets_lite/high_level_vision/decomposition"

["src/generate_datasets/high_level_vision/same_different_task/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
type_dataset = "all"
size_shapes = 20
output_folder = "datasets_lite/high_level_vision/same_different_task"

["src/generate_datasets/high_level_vision/gridded_images/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix"
object_longest_side = 100
grid_degree = 45
grid_size = 8
grid_thickness = 4
output_folder = "datasets_lite/high_level_vision/gridded_images"

["src/generate_datasets/low_level_vision/ebbinghaus_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
output_folder = "datasets_lite/low_level_vision/ebbinghaus_illusion"

["src/generate_datasets/low_level_vision/size_constancy_ponzo/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_scrambled = 100
num_samples_illusory = 50
num_rail_lines = 5
train_with_rnd_col_lines = false
output_folder = "datasets_lite/low_level_vision/size_constancy_ponzo"

["src/generate_datasets/low_level_vision/contour_completion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 100, 100, 100,]
antialiasing = true
regenerate = true
num_samples = 100
circle_color = [ 255, 255, 255,]
square_color = [ 0, 0, 0,]
output_folder = "datasets_lite/low_level_vision/contour_completion"

["src/generate_datasets/low_level_vision/tilt_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_only_center = 100
num_samples_center_context = 100
output_folder = "datasets_lite/low_level_vision/tilt_illusion"

["src/generate_datasets/low_level_vision/webers_law/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_per_length = 100
max_line_length = 50
min_line_length = 5
interval_line_length = 1
output_folder = "datasets_lite/low_level_vision/webers_law"

["src/generate_datasets/low_level_vision/muller_lyer_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_scrambled = 100
num_samples_illusory = 50
output_folder = "datasets_lite/low_level_vision/muller_lyer_illusion"

["src/generate_datasets/low_level_vision/jastrow_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples_illusory = 50
num_samples_random = 50
num_samples_aligned = 50
output_folder = "datasets_lite/low_level_vision/jastrow_illusion"

["src/generate_datasets/gestalt/thatcher_illusion/generate_dataset.py"]
canvas_size = [ 224, 224,]
face_folder = "assets/celebA_sample/normal"
output_folder = "datasets_lite/gestalt/thatcher_illusion"
regenerate = true

["src/generate_datasets/gestalt/dotted_linedrawings/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
object_longest_side = 100
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
dot_distance = 5
dot_size = 1
output_folder = "datasets_lite/gestalt/dotted_linedrawings"

["src/generate_datasets/gestalt/texturized_linedrawings_chars/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
num_samples = 100
object_longest_side = 200
background_char = "\\"
foreground_char = "."
output_folder = "datasets_lite/gestalt/texturized_linedrawings_chars"

["src/generate_datasets/gestalt/leuven_embedded_figures_test/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
output_folder = "datasets_lite/gestalt/leuven_embedded_figures_test"

["src/generate_datasets/gestalt/CSE_CIE_dots/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
output_folder = "datasets_lite/gestalt/CSE_CIE_dots"

["src/generate_datasets/gestalt/un_crowding/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
num_samples_vernier_inside = 100
num_samples_vernier_outside = 100
random_size = true
output_folder = "datasets_lite/gestalt/un_crowding"

["src/generate_datasets/gestalt/texturized_linedrawings_lines/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = false
regenerate = true
linedrawing_input_folder = "assets/baker_2018/outline_images_fix/"
num_samples = 100
object_longest_side = 200
density = 1.8
output_folder = "datasets_lite/gestalt/texturized_linedrawings_lines"

["src/generate_datasets/gestalt/embedded_figures/generate_dataset.py"]
canvas_size = [ 224, 224,]
background_color = [ 0, 0, 0,]
antialiasing = true
regenerate = true
num_samples = 100
shape_size = 45
debug_mode = false
output_folder = "datasets_lite/gestalt/embedded_figures"
