[basic_info]
annotation_file_path = 'datasets/gestalt/CSE_CIE_dots/annotation.csv'
match_factors = ['SampleId']
filter_factor_level = { Type = "linearity" }
factor_variable = "PairA/B"
reference_level = "a"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/CSE_CIE_dots/linearity"

[transformation.values]
translation = false
scale = false
rotation = false
