[basic_info]
annotation_file_path = 'data/gestalt/CSE_CIE_dots/annotation.csv'
match_factors = ['SampleId']
filter_factor_level = { Type = "proximity"}
factor_variable = "PairA/B"
reference_level = "a"

[options]
pretraining = "ImageNet"

[saving_folders]
result_folder = "results/similarity_judgments/CSE_CIE_dots/proximity"

[transformation]
affine_transf_code = ""
