[basic_info]
annotation_file_path = 'data/high_level_vision/decomposition/annotation.csv'
match_factors = ['SampleId']
filter_factor_level = { ShapeType = "familiar" }
factor_variable = "SplitType"
reference_level = "no_split"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/decomposition/familiar"

[transformation]
affine_transf_code = "t[-0.2, 0.2]r[-50, 50]s[0.8, 1.2]"
affine_transf_background = [0, 0, 0]
matching_transform = true
repetitions = 50
