[basic_info]
annotation_file_path = 'datasets/high_level_vision/decomposition/annotation.csv'
filter_factor_level = { ShapeType = "unfamiliar" }
match_factors = ['SampleId']
factor_variable = "SplitType"
reference_level = "no_split"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/decomposition/unfamiliar"

[transformation]
fill_color = [0, 0, 0]
matching_transform = true
repetitions = 50

[transformation.values]
translation = [-0.2, 0.2]
scale = [0.8, 1.2]
rotation = [-50, 50]
