[basic_info]
annotation_file_path = 'datasets/coding_of_shapes/NAPvsMP_3D_geons/annotation.csv'
match_factors = ["SampleName"]
factor_variable = "Type"
reference_level = "reference"

[options]
pretraining = "ImageNet"

[saving_folders]
results_folder = "results/similarity_judgments/NAPvsMP_3D_geons"

[transformation]
affine_transf_background = [0, 0, 0]
matching_transform = true
repetitions = 50

[transformation.values]
translation = [-0.2, 0.2]
scale = [0.8, 1.2]
rotation = [-50, 50]
