task_type = "classification"

[network]
load_path = "models/examples/decoder/embedded_figures_classification/trained_model/checkpoint_model.pt"
batch_size=16

[saving_folders]
results_folder = "results/examples/decoder/embedded_figures_classification/test"


[[eval.datasets]]
name = "embedded"
annotation_file = "datasets_examples/embedded_figures/annotation.csv"
img_path_col_name = "Path"
label_cols = ["PolygonId"]
filters = { Type = "embedded_polygon" }


[transformation]
fill_color = [0, 0, 0]
[transformation.values]
translation = [-0.2, 0.2] 
scale = [0.7, 1.3]
rotation = [0, 360]