[training]
type_training = "regression"

[datasets.training]
name = "train_random"
annotation_file = "data/low_level_vision/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "random" }

# [[datasets.validation]]
# name = "val_aligned"
# annotation_file = "data/low_level_vision/sss_jastrow_illusion/annotation_w_diff.csv"
# img_path_col_name = "Path"
# label_cols = ["DiffSizeTopBottom"]
# filters = { Type = "aligned"}


# [[datasets.validation]]
# name = "val_illusory"
# annotation_file = "data/low_level_vision/sss_jastrow_illusion/annotation_w_diff.csv"
# img_path_col_name = "Path"
# label_cols = ["DiffSizeTopBottom"]
# filters = { Type = "illusory"}



[monitoring]
neptune_proj_name = false