[input_paths]
reference_name = "data/examples/NAPvsMPlines/NS"
folder = "data/examples/NAPvsMPlines"

[options]
pretraining = "ImageNet"

[saving_folders]
 result_folder = "results/examples/distance_similarity/ImageNet/NAPvsMPlines/"

[transformation]
repetitions = 5