task_type = "regression"

[training]
evaluate_during_training = false

[training.dataset]
name = "train_random"
annotation_file = "datasets_examples/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "random" }

[training.monitoring]
neptune_proj_name = false

[saving_folders]
results_folder = "results/examples/decoder/jastrow_regression"
model_output_folder = "models/examples/decoder/jastrow_regression"

# Since training.evaluate_during_training is false, these two datasets won't be evaluated. 
[[eval.datasets]]
name = "eval_aligned"
annotation_file = "datasets_examples/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "aligned" }


[[eval.datasets]]
name = "val_illusory"
annotation_file = "datasets_examples/jastrow_illusion/annotation_w_diff.csv"
img_path_col_name = "Path"
label_cols = ["DiffSizeTopBottom"]
filters = { Type = "illusory" }

[transformation]
translation = [-0.2, 0.2] 
scale = [0.7, 1.3]
rotation = [0, 360]