[input_paths]
base_name = "data/examples/closure/square.png"
folder = "data/examples/closure/angles_rnd"

[options]
pretraining = "ImageNet"

[saving_folders]
 result_folder = "results/examples/distance_similarity/ImageNet/scrambled_square"

[transformation]
repetitions = 5