name: Python CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    # -------- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        python-version: ["3.9.6"]

    steps:
      # -------- https://github.com/actions/checkout
      # check out your repository files onto the runner, so that the workflow can access them
      - uses: actions/checkout@v4

      # -------- https://github.com/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # --------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          pip install -r requirements.txt
      # --------
      - name: Format with black
        run: |
          black . --check --line-length=88

      # --------
      - name: Test with pytest
        run: |
          pytest
